version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "workbench-step-functions"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t5mbijacetch"
s3_prefix = "workbench-step-functions"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
